### ISSUE TITLE
Hyphenation with vs-formatter

### ISSUE THREAD

**Issue by zopyx** [Trimmarks/vivliostyle-formatter-issues#19]
The documentation say about hyphenation:

hyphens
Allowed prefixes: epub, moz, ms, webkit

Hyphenation does not seem to work with vs-formatter at all (not with hyphens: webkit | auto).
Values 'ms', 'moz', 'epub' don't make much sense for the vs-formatter.

**Comment by frivoal** [comment]
`hyphens` is delegated to the browser engine, (the doc says "Depends on browser's capability: Yes"). The unfortunately, the chrome engine only support `none` and `manual`, and not `auto`, meaning the same is true of Vivliostyle Formatter. We know this is an issue, and are weighing our options to work around that limitation.

As for the prefixes, which of the supported prefixes you use makes no difference to how we process it, so if you're writing style sheets from scratch for Vivliostyle, using no prefix is the path of lease resistance. The reason we support the prefixes is for compatibility with existing content which often uses only one or some of the prefixes.

**Comment by esetera** [comment]
What would be the order of execution if I were to use an script like Hyphenator.js ... can I somehow insert this into the rendering process at the right moment to take care of hyphens?

**Comment by zopyx** [comment]
You  have no option right now to inject something into the rendering
process...in particular because VS-formatter does not support any JS on the
input side at the moment.  Hyphenation must be a build-in feature of VS.

**Comment by esetera** [comment]
ok, interesting. Any idea of effort involved to 
1) build some mechanism to inject JS into the rendering process
2) build hyphenation support into VS

**Comment by zopyx** [comment]
Ask VS since the formatter is closed-source...very little options to help
here.

2016-07-10 16:55 GMT+02:00 adam notifications@github.com:

**Comment by esetera** [comment]
But the formatter uses the same JS engine as the standard VS JS right? The standard vs.js is open...

**Comment by frivoal** [comment]
The Formatter uses the same js engine as the standard viviliostyle.js, that is right. And yes, it is open.

One reason we have not developed this feature ourselves yet is that chrome seems to be on the verge of supporting it natively, and once they do, we automatically gain this support as well: https://bugs.chromium.org/p/chromium/issues/detail?id=605840

If chrome fails to deliver, this is the path we are most likely to pick an existing js hyphenation library/polyfill, and integrate it into vivliostyle.js somewhat similarly to how we integrate mathjax. If anyone wants to send us patches and pull requests, we will be happy to look at it.

Finally, another approach would be to enable a mode in vivliostyle viewer and vivliostyle formatter which works similarly to the vivliostyle browser extension: instead of having the js load the document, we would let the browser do that, including running inline / onload/... scripts, and them  apply the vivilostyle formatting magic. This would be more flexible for end-users, as it would allow anyone to load any javascript they want, but it is also in a way less powerful that directly integrating a js hyphenation engine, as it would have to be scripts that run initially, not scripts that can be intertwined with layout.

**Comment by esetera** [comment]
Thanks Florian. From what I read relying on hyphenation dictionaries in browsers is a little iffy at best. If there is an opportunity to load our own scripts that would be a good option even if there was native browser support. Then we get the best of both worlds :) Running JS also would allow users to leverage things like typography scripts of which there is a growing number online that are very useful.

**Comment by MurakamiShinyu** [comment]
This issue was moved to vivliostyle/vivliostyle.js#420

**Comment by kwkbtr** [comment]
Hyphenation has been supported since Vivliostyle Formatter 2017.2.
